### ISSUE TITLE
Unable to download `-android` version of the library via Gradle.

### ISSUE THREAD

**Issue by elliottj-accolade** [Babylonpartners/certificate-transparency-android#14]
Android Studio details:
```
Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 1, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
```

Repro steps:
1. Add `implementation 'com.babylon.certificatetransparency:certificatetransparency-android:0.1.2'` to build.gradle dependencies.
2. Attempt to Sync Project with Gradle files
3. Note failure: `ERROR: Failed to resolve: com.babylon.certificatetransparency:certificatetransparency-android:0.1.2`

Additional Details:
* Regular Java dependency resolves just fine: `implementation 'com.babylon.certificatetransparency:certificatetransparency:0.1.2'`
* Previous version of `-android` (0.1.1) resolves without issue: `implementation 'com.babylon.certificatetransparency:certificatetransparency-android:0.1.1`
* Attempted to clean / invalidate and restart with no luck.
* Added the maven url (`maven { url 'https://dl.bintray.com/babylonpartners/maven' }`) to my repositories in the `build.gradle` file, which I hadn't needed to do before, and it still didn't resolve.

Let me know if there's something else I can try...

**Comment by mattmook** [comment]
Probably a mistake on my part as there wasn’t any code previously on the Android side. As I’m away I won’t be able to look at this till next week though

**Comment by mattmook** [comment]
Weirdly the build is no longer finding the sources, javadocs and more importantly the pom file to upload, hence why the dependency doesn't work. The same is happening for the main lib also so none of it is working!

**Comment by mattmook** [comment]
@elliottj-accolade this should hopefully be fixed in 0.1.4. I'm having some computer issues so I've been able to verify this myself but can at least see the expected files in Bintray (which didn't show before): 

https://dl.bintray.com/babylonpartners/maven/com/babylon/certificatetransparency/certificatetransparency-android/0.1.4/

**Comment by elliottj-accolade** [comment]
This issue is technically fixed, as I can now download the `...-android:0.1.4` version, but my original issue (https://github.com/Babylonpartners/certificate-transparency-android/issues/5) is still occurring. @mattmook would you like me to re-open that issue, or create a new one?
